apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secrets
spec:
  provider: azure
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
      - objectName: db-password
        key: password
  parameters:
    usePodIdentity: "false"
    keyvaultName: devops-keyvault
    tenantId: "e0abc987-dc31-4881-bb37-3629931d077b"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
